openstack-k8s-operators/dev-docs

common_issues.md
Add lib-common unknown revision 000000000000 problem to list of known issues with workaround.
=> Document lib-common unknown revision 000000000000

developer.md
Depends on https://github.com/openstack-k8s-operators/docs/pull/5
=> Passing deps by name

developer.md
Depends on https://github.com/openstack-k8s-operators/docs/pull/6
=> Child objects and finalizers

developer.md
This is based on @mdbooth's excellent [comment](https://github.com/openstack-k8s-operators/ovn-operator/pull/1#discussion_r997014701)
=> Return after self Update() or Patch()

developer.md
Thanks to @stuggi we have a solution for properly defaulting struct fields.
=> Document how to default struct fields in CRD

README.md, kuttl_tests.md
Add some basic documentation for writing kuttl tests. The goal is to
capture some common pitfalls/tricks when using kuttl and make clear
which conventions have been used to achieve consistency.
=> Add some documentation for kuttl tests

test_strategy.md
This is based on the comment from @stuggi in https://github.com/openstack-k8s-operators/docs/pull/20
=> [test-strategy]Add infra-operator specific rules

ceph.md
Add steps to Ceph documentation to include using CephFS with Manila.
=> Document using Manila with Ceph

README.md, ceph.md, extra_mounts.md
Document extraMounts and extraVol
Co-authored-by: Francesco Pantano - fpantano@redhat.com
=> Document extraMounts and extraVol

test_strategy.md
This is based on the comments from @stuggi in
https://github.com/openstack-k8s-operators/docs/pull/20
=> [test-strategy]Add lib-common specific rules

running_local_operator.md, webhooks.md
Updates to "running local operator" doc for better clarity around the process involved
=> Consolidate steps for running local operator

webhooks.md
Explains how to modify an OLM-deployed CSV for a given operator in order to change the default env var values (currently useful for changing the default container images)
=> Describe procedure for updating CSV env var defaults

hci.md
Document how to use the ceph-hci-pre service when deploying HCI to configure the firewall for Ceph services.
Jira: OSP-25827
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/341
=> Add documentation on using the ceph-hci-pre service

ceph.md, hci.md
It is no longer supported [1] to use a `nova` dictionary within a `OpenStackDataPlane` CR to pass configuration overrides to Nova. Instead the overrides should be stored in a `ConfigMap` and a custom version of the `nova service` should reference it using `configMaps` within an `OpenStackDataPlaneService` CR.
Re-write Ceph/HCI documents so that reader can get the same configuration as before but using the new method.
[1] https://github.com/openstack-k8s-operators/dataplane-operator/pull/337
=> Update Ceph/HCI documents for dataplane configMaps update

ceph.md
Document using multiple Ceph keyrings in a secret CR. Document where ceph files are stored on EDPM nodes. Update Manila example to include missing pools.
Update ceph-nova custom service example with playbook as it has recently changed.
Jira: OSP-27777
=> Update Ceph documentation for recent changes

ceph.md
This patch introduces a section that describes how to configure a `RadosGW` instance as a backend for the 
`OpenStack` `Object-Store` service.
=> Add external RGW backend for Object-Store service

hci.md
Link to new HCI sample in dataplane-operator provided by the depends-on patch.
Jira: OSP-28997
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/448/
=> Update network section of HCI documenation

hci.md
Use servicesOverride feature of OpenStackDataPlaneDeployment to make HCI documentation more clear. Instead of having human operator edit the services list before creating a second deployment, provide two deployment examples which can be run before and after Ceph is deployed.
This patch links to samples which will be introduced by the Depends-On patch so please merge it first.
Jira: OSP-29040
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/464
=> Update HCI documentation to use pre/post Ceph deployments

developer.md
This patch adds the explanation for the changes that incorporate the below :
This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-05-18T02:00:28+03:00       INFO    Controllers.KeystoneAPI Reconciled Service init successfully    {"controller": "keystoneapi", "controllerGroup": "keystone.openstack.org", "controllerKind":"KeystoneAPI", "KeystoneAPI": {"name":"keystone","namespace":"openstack"}, "namespace": "openstack", "name": "keystone", "reconcileID": "512a4d9b-f31d-4fa4-a4cc-cd6c13e4455d"}
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and …
=> switch to structured logging

debugging.md
... and add reference to the relevant section in
running_local_operator.md.
=> Add kubefwd related config to VSCode run config

README.md, tls.md
=> [TLS] initial tls documentation

README.md, troubleshooting.md
Implements: [OSPRH-4290](https://issues.redhat.com//browse/OSPRH-4290)
=> Add troubleshooting doc

tls.md
=> [TLS] internal tls documentation

troubleshooting.md
=> Document Ceph Client Troubleshooting

README.md, ovs-update.md
An attempt to capture the mechanics of the situation and to propose the path forward for OVS updates during adoption and on new OVS (image or package) release in general.
=> OVS update design proposal

tls.md
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/789
=> [tls] update default duration

nfv_ovs_dpdk.md
This change is to add the document for NFV OVS DPDK EDPM deployment guide.
=> NFV OVS DPDK document changes

tls.md
This patch describes the implementation of a mechanism to add `Subject Alternative Name` `DNS` entries to the `Certificate` Requests.
An operator can provide to the `Service` the `Annotation` described by this patch to get the additional entries processed by the `openstack-operator`.
Jira: https://issues.redhat.com/browse/OSPRH-7276
=> Additional Subject Alternative Names to TLS doc section

extra_mounts.md
This patch improves the `extraMounts` description with more details that might be useful to produce documentation.
Related: https://issues.redhat.com/browse/RHOSPDOC-1627
=> Improve extraMounts docs with samples and a few additional details

nfv_sriov.md
This change is to add the deployment guide for NFV SRIOV.
=> NFV SRIOV document changes

nfv_ovs_dpdk.md
This change is to fix NFV OVS DPDK document issues.
=> NFV OVS DPDK document issues fix

troubleshooting.md
This patch updates the `Ceph` troubleshooting guide to use a debug (`Glance`) `Pod` to run `rbd` commands against the `Ceph` cluster. `Glance` is connected to the storage network through the proper `NAD`, and it's a good fit to provide a `Ceph` troubleshooting example.
Jira: [OSPRH-839](https://issues.redhat.com/browse/OSPRH-839)
=> Update Ceph troubleshooting guide

troubleshooting.md
The `nc` command is not installed on the Glance pod so we cannot suggest it be used to test the pod's connection to Ceph. Instead the procedure is re-written using a Python socket since that has confirmed to be available in the Glance pod.
=> Troubleshoot Ceph network connection without nc

troubleshooting.md
Signed-off-by: James Slagle <jslagle@redhat.com>
=> Add docs for debugging ansible

conditions.md
Some updates to clarify that we want conditions to indicate that a given spec has been applied and the services are running with that active configuration.
=> Updates to conditions.md

troubleshooting.md
ref: https://github.com/openstack-k8s-operators/edpm-ansible/pull/788
=> Update edpm_entrypoint path

envtest.md
There were some punctuation failures and minor cosmetic problems on the text. This patch fixes them.
=> Cosmetic and Punctuation Fixes

README.md, edpm_update_overview.md
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/911
Signed-off-by: James Slagle <james.slagle@gmail.com>
=> Add edpm update overview docs

version_updates.md
Preview: https://gist.github.com/fmount/75f98ba1e9789ff25262607f86ace521
=> Add serviceDefaults description in openstackVersion

conditions.md, developer.md, envtest.md
This change update outdated url references with new ones. Some were giving 404 (not found) error and others are updated with github permalink.
=> Update url references

nfv_ovs_dpdk.md, nfv_sriov.md, running_local_operator.md, webhooks.md
- Update broken links to non-existent ovs_dpdk.md and sriov.md
- Update web links to mention dev-docs repo instead of docs repo
=> Fix broken links
