developer.md
Start documenting best practices / rule of thumbs for operator development. This patch also adds to guideline one for logging from the operator code and one for k8s client usage.
=> Add a developer guide

README.md
We are missing the link to the developer guidelines in the README file.
=> Add guidelines link to README

README.md, operator_controller_labels.md
Document describing how we approach operator `controller-manager` pod labeling such that it suits both aggregate and unique selection purposes.
=> Operator controller-manager pod labels doc

running_local_operator.md
```
❯ export OPERATOR_NAME="dataplane-operator"
❯ OPERATOR_INDEX=$(oc get csv openstack-operator.v0.0.1 -o json | jq -r '.spec.install.spec.deployments | map(.name == $ENV.OPERATOR_NAME + "-controller-manager") | index(true)')
❯ echo $OPERATOR_INDEX                                                                                                                                                         
6
❯ oc patch csv openstack-operator.v0.0.1 --type json \
-p "[{ "op": "remove", "path": "/spec/install/spec/deployments/${OPERATOR_INDEX}" }]"
clusterserviceversion.operators.coreos.com/openstack-operator.v0.0.1 patched
```
=> Improved the way how deployment index is gathered from csv and the patching procedure

webhooks.md
Operators are now installed in `openstack-operators` namespace, so the CSV location has changed
=> Update local webhook doc for new operator namespace paradigm

README.md, ceph.md
This document describes how to use CRs from the
openstack-k8s-operators project to configure OpenStack so that Glance, Cinder, and Nova use block storage from an external Ceph cluster. It does not require the use of install_yamls.
=> Document Ceph RBD Configuration

webhooks.md
The local webhooks instructions are simplified now that we no longer bundle service operators within the OpenStack operator
=> Update local webhooks procedure for new operator bundling

README.md, service_config.md
The patch represents a proposal to find a common pattern for services bootstrap.
=> Propose Service Bootstrap config design

networking.md
IPs need to be configured on isolated network interfaces to have proper routing for the traffic coming via metallb vip into the cluster. If non is set, the return path back from the pod to the client will use the default GW since metallb does not do NAT and there is no association to the isolated network interface. nmstate right now also does not allow to create a route like `ip route add 192.168.122.0/24 dev enp6s0`. It gets blocked on validation since IPv4 is disabled for the interface.
=> Configure IPs on isolated networks interfaces

running_local_operator.md
Update the instructions for creating a backup of the operator's CSV. The command needs to remove the /metadata/uid because that field is immutable.
=> Update instructions for running local operator

envtest.md
The test helpers were restructured with [1].
Update doc to reflect it.
[1] https://github.com/openstack-k8s-operators/lib-common/pull/301
=> [envtest] Fix helper links after reorg

ceph.md, hci.md
It is now necessary to include the ceph-client service when configuring Ceph or HCI so update documents accordingly.
Jira: OSP-25826
=> Document EDPM ceph-client service

README.md, edpm_service_overview.md
Provide a starting point in the main openstack-k8s-operators docs repository which gives an overview of how to start writing an EDPM service which links to the more detailed documentation from the Data Plane Operator and EDPM Ansible projects. Also, provide common patterns which other EDPM services use to solve common problems.
=> Document Overview of  Configuring Services on EDPM Nodes

ceph.md, edpm_service_overview.md, hci.md
The OpenStackDataPlaneNodeSet CRD has been introduced to the data plane operator so the Ceph documentation needs to be updated to work with the new CRD.
Also, ceph-hci-pre needs to come before configure-os, as the latter is what actually applies the firewall rules that the former generates.
=> Update Ceph docs for OpenStackDataPlaneNodeSet

networking.md
Jira: OSP-26690
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/457
=> Update networking doc for service override change

ceph.md
EDPM nodes resolve the internal endpoint associated with a given service. This change fixes the doc where we previously suggested to add the "ceph config global set rgw_keystone_url" pointing to the identity public endpoint.
=> Fix external RGW doc to point to keystone internal endpoint

hci.md
Fix bug introcued in b3530aa98ac6fad6492487346bd41d0d4f9ca9d2 where dataplane_v1beta1_openstackdataplanenodeset_hci.yaml should be dataplane_v1beta1_openstackdataplanenodeset_ceph_hci.yaml when linking to the dataplane operator sample configuration.
=> Update 404'ing link to HCI example

running_local_operator.md
Add some missing information about how to determine the CSV of the dataplane-operator so that it can be scaled down for local development.
=> Document dataplane-operator scale down for local work

networking.md
Now that glance has a new CRD and API definition, we need an updated doc to avoid confusion between the old and the new version.
=> Align glanceAPI to the new CRD and update the associated samples

service_config.md
OVN has no use for kolla config file management. Kolla just gets in the way by putting additional requirements as to permissions on top of what OVN services actually may need.
=> Clarify that service_config is for oslo.config services

fips.md
This patch adds general information and the steps required to build a fips compatible operator images.
=> FIPS support for the openstack-operators

fips.md
Operators should be reporting in their annotations when they are fully supporting FIPS.
This PR documents this.
=> FIPS: Mention the feature reporting

ceph.md
RGW is not a backend for Swift, we technically create and configure the object store service to use an external element (RGW) that exposes the same Swift API. In this scenario swift is not deployed at all via the swift-operator.
=> Fix RGW/Swift section name

ceph.md
Now that the Glance Operator configures this automatically we do not have to tell the user to configure it with extra steps.
=> Update Ceph RBD Glance Image Conversion

testing_openstack_code_changes_with_operators.md
This patch adds guide about how to easily test locally changes in the OpenStack code on the podified environment. This method can also be used for the development workflow, not only testing.
This document is based on the similar guide from the edpm-ansible repo [1] which is about testing edpm-ansible roles with ansibleee operator.
[1] https://github.com/openstack-k8s-operators/edpm-ansible/blob/main/docs/source/testing_with_ansibleee.rst
Related: #OSP-26653
=> Add guide about testing locally openstack code changes with podified env

testing_openstack_code_changes_with_operators.md
This patch adds new section to the document about how to test together OpenStack code changes together with changes made for operators. This new section is about doing such testing in the operator's CI jobs.
Closes: #OSP-26653
=> Testing u/s changes together with operator changes in the CI

tls.md
Depends-On: openstack-k8s-operators/openstack-operator/pull/797
=> [tls] Add kuttl scenarios description

testing_openstack_code_changes_with_operators.md
Both the PV and the PVC claiming a specific PV, should have the same ``storageClassName``.
This patch is also fixing the Neutron
``extraVol.volumes.persistentVolumeClaim.claimName``, matching the one assigned to the created PVC.
=> Fix the PersistentVolumeClaim storageClassName

ceph.md, hci.md
It was reported that edpm-update services skips container update tasks for custom services. However, we found this was because the services list for the HCI deployment where we teseted was missing the run-os service. This service was missing since the second deploy excluded it since HCI uses two deploys. That's fine, provided the full service list is restored at the end.
This change documents that you must recombine the service list and describes how to do it.
=> HCI nodesets must have complete services list post deploy

webhooks.md
Rather than outright removing `/spec/webhookdefinitions` from a CSV, we should instead document replacing them with an empty array.  This is preferable because it can be executed again without returning an error, unlike the removal which fails if the path does not exist.
=> Improve patch command for removing webhook defs from CSV

custom_openstack_operator.md, running_local_operator.md, webhooks.md
Our developer documentation for running local operators and/or webhooks needs to be updated in light of the new install paradigm [1].  There are certain limitations that are now encountered that currently restrict the options for local deployments.
[1] https://dprince.github.io/openstack-operator-initialization-resource.html
=> Update local operator/webhooks docs for new install paradigm

webhooks.md
This change updates the webhook doc NOTE mentioning that the `oc delete` on `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration` resources created by `make run-with-webhook` command, run automatically when it receives SIGINT or SIGTERM signal.
Also add the command to scale-up the replicas of controller-manager which was scale-down with `make run-with-webhook` command.
=> Update webhook doc
